[package]
name = "proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
arti-client = "0.42.0"
async-trait = "0.1.89"
http = "1.4.0"
httparse = "1.10.1"
pingora = { version = "0.8.0", features = ["proxy", "cache"] }
pingora-memory-cache = "0.8.0"
rustls = { version = "0.23.35", default-features = false, features = ["ring", "std"] }
rustls-pemfile = { version = "2.2.0", default-features = false, features = ["std"] }
tokio = "1.52.3"
tokio-rustls = { version = "0.26.4", default-features = false, features = ["ring"] }
tor-rtcompat = "0.42.0"
